using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
public static class SKGenerator
{
    private const string OutputPath = "Assets/ScriptFramework/Audio/SK.cs";

    public static void Generate(List<AudioEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> 由 AudioManager 自动生成，请勿手动修改 </auto-generated>");
        sb.AppendLine("// SK — 音效枚举，在 AudioManager Inspector 点\"生成 SK 枚举\"刷新");
        sb.AppendLine("// 用法：AudioManager.instance.Play(SK.治疗);");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("public enum SK");
        sb.AppendLine("{");

        var enumToKey = new List<(string enumName, string key)>();
        var seen = new HashSet<string>();

        foreach (var entry in entries)
        {
            if (string.IsNullOrEmpty(entry.key)) continue;
            string enumName = ToEnumName(entry.key);
            if (!seen.Add(enumName)) continue;
            enumToKey.Add((enumName, entry.key));
            sb.AppendLine($"    {enumName},");
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // 静态映射表，供 AudioManager.Play(SK) 查找原始 key
        sb.AppendLine("public static class SKMap");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly Dictionary<SK, string> Keys = new Dictionary<SK, string>");
        sb.AppendLine("    {");
        foreach (var (enumName, key) in enumToKey)
            sb.AppendLine($"        {{ SK.{enumName}, \"{key}\" }},");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        string fullPath = Path.GetFullPath(Path.Combine(Application.dataPath, "../", OutputPath));
        string existing = File.Exists(fullPath) ? File.ReadAllText(fullPath) : null;
        string generated = sb.ToString();

        // 统一换行符再比较，避免 \r\n 和 \n 差异导致误判
        if (existing != null && existing.Replace("\r\n", "\n") == generated.Replace("\r\n", "\n")) return;

        File.WriteAllText(fullPath, generated, Encoding.UTF8);
        AssetDatabase.ImportAsset(OutputPath);
    }

    private static string ToEnumName(string key)
    {
        // 保留字母、数字、中文，其余替换为下划线
        string result = Regex.Replace(key, @"[^a-zA-Z0-9一-鿿]", "_").Trim('_');

        if (string.IsNullOrEmpty(result))
            return $"Key{(uint)key.GetHashCode():X}";

        if (char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }
}
