// <auto-generated> 由 AudioManager 自动生成，请勿手动修改 </auto-generated>
// SK — 音效枚举，在 AudioManager Inspector 点"生成 SK 枚举"刷新
// 用法：AudioManager.instance.Play(SK.治疗);
using System.Collections.Generic;

public enum SK
{
    BGM,
    结算BGM,
    投金币,
    收金币,
    物品,
    丢入锅,
    老鼠叠高高,
    警告_缺金币,
    警告_满,
    治疗,
    治疗完成,
    解锁,
    解锁_建筑,
    图标出现,
    启动按钮,
    结算页面弹出,
    割草,
    吸尘器,
    老鼠叫,
}

public static class SKMap
{
    public static readonly Dictionary<SK, string> Keys = new Dictionary<SK, string>
    {
        { SK.BGM, "BGM" },
        { SK.结算BGM, "结算BGM" },
        { SK.投金币, "投金币" },
        { SK.收金币, "收金币" },
        { SK.物品, "物品" },
        { SK.丢入锅, "丢入锅" },
        { SK.老鼠叠高高, "老鼠叠高高" },
        { SK.警告_缺金币, "警告-缺金币" },
        { SK.警告_满, "警告-满" },
        { SK.治疗, "治疗" },
        { SK.治疗完成, "治疗完成" },
        { SK.解锁, "解锁" },
        { SK.解锁_建筑, "解锁-建筑" },
        { SK.图标出现, "图标出现" },
        { SK.启动按钮, "启动按钮" },
        { SK.结算页面弹出, "结算页面弹出" },
        { SK.割草, "割草" },
        { SK.吸尘器, "吸尘器" },
        { SK.老鼠叫, "老鼠叫" },
    };
}
